site_name: Technical Documentation
theme:
  name: material
  custom_dir: docs/assets/overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: flaredark
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  logo: logo.svg                # Put it in the overrides folder!
  favicon: assets/favicon.png
  features:
    - navigation.tabs           # Top-level pages are shown as tabs on the header
    - navigation.tabs.sticky    # Navigation tabs are always visible
    - navigation.top            # "Back to top" button appears upon upward scrolling
    - navigation.indexes        # Allow section headers to have a page (see tech/index.md)
    - content.tabs.link
markdown_extensions:
  - admonition                  # Info boxes (in different colors)
  - pymdownx.details            # "
  - pymdownx.superfences        # Info boxes, tabs
  - pymdownx.caret              # Allow superscript and insertion marks (^ and ^^)
  - pymdownx.tilde              # Allow subscript and deletion marks (~ and ~~)
  - pymdownx.keys               # Allow Keyboard marks (++)
  - pymdownx.mark               # Allow selection marks (==)
  - pymdownx.inlinehilite       # Syntax-highlight inline code
  - pymdownx.tabbed:            # Tabbed content
      alternate_style: true
  - toc:                        # TOC control
      permalink: "#"            # Add permalinks to headers
  - pymdownx.arithmatex:        # Math blocks
      generic: true
  - attr_list                   # { Annotations }
  - md_in_html                  # Markdown inside HTML
  - def_list                    # Definition lists (Glossary)
  - pymdownx.snippets           # Import files with --8<--
plugins:
  - search                      # Search box at the top
  - git-revision-date           # Last edit timestamp at the bottom
  - autolinks                   # Use just filenames instead of full or relative paths
  - redirects:                  # Allow creating redirects for moved pages
      redirect_maps:
          'en/state-connector.md':  'tech/state-connector.md'
          'technology/glossary.md': 'tech/glossary.md'
          'technology/state-connector.md': 'tech/state-connector.md'
          'networks/songbird.md': 'dev/reference/network-configs.md'
          'networks/coston-testnet.md': 'dev/reference/network-configs.md'
          'tutorials/wallets/index.md': 'user/wallets/index.md'
          'tutorials/wallets/bifrost-wallet.md': 'user/wallets/bifrost-wallet.md'
          'tutorials/wallets/dcent-wallet.md': 'user/wallets/dcent-wallet.md'
          'tutorials/wallets/how-to-access-flare-network-with-a-ledger-device.md': 'user/wallets/how-to-access-flare-network-with-a-ledger-device.md'
          'tutorials/wallets/how-to-access-flare-network-with-a-trezor-device.md': 'user/wallets/how-to-access-flare-network-with-a-trezor-device.md'
          'tutorials/wallets/how-to-access-flare-network-with-metamask.md': 'user/wallets/how-to-access-flare-network-with-metamask.md'
          'tutorials/wallets/safepal-s1-wallet.md': 'user/wallets/safepal-s1-wallet.md'
          'tutorials/wallets/brave-wallet.md': 'user/wallets/brave-wallet.md'
          'tutorials/explorer/songbird-explorer.md': 'user/block-explorer.md'
          'tutorials/explorer/coston-explorer.md': 'user/block-explorer.md'
          'tutorials/developing-on-top-of-flare/README.md': 'dev/index.md'
          'tutorials/developing-on-top-of-flare/important-links.md': 'dev/index.md'
          'tutorials/delegation/README.md': 'user/delegation/index.md'
          'tutorials/delegation/delegation-in-detail.md': 'user/delegation/delegation-in-detail.md'
          'tutorials/delegation-faq/README.md': 'user/delegation/delegation-faq.md'
          'tutorials/delegation-faq/block-explorer-+-metamask.md': 'user/delegation/manual-delegation.md'
          'tutorials/reward-claiming/README.md': 'user/delegation/reward-claiming.md'
          'tutorials/reward-claiming/reward-claiming-in-detail.md': 'user/delegation/reward-claiming-in-detail.md'
          'tutorials/reward-faq/README.md': 'user/delegation/reward-claiming-faq.md'
          'tutorials/reward-faq/block-explorer-+-metamask.md': 'user/delegation/manual-reward-claiming.md'
          'tutorials/price-provider/setting-up-an-observation-node/README.md': 'infra/observation/deploying.md'
          'tutorials/price-provider/setting-up-an-observation-node/observation-node-faq.md': 'infra/observation/deploying.md'
          'tutorials/price-provider/ftso-price-provider/README.md': 'infra/data/operating.md'
          'tutorials/price-provider/ftso-price-provider/price-provider-faq.md': 'infra/data/operating.md'
          'tutorials/price-provider/ftso-price-provider/whitelisting-a-price-provider.md': 'infra/data/whitelisting.md'
          'tutorials/price-provider/ftso-price-provider/whitelisting-price-provider-faq.md': 'infra/data/whitelisting.md'
          'tutorials/price-provider/troubleshooting/price-provider.md': 'infra/data/operating.md'
          'infra/data/deploying.md':  'infra/data/operating.md'
          'tutorials/price-provider/troubleshooting/observation-node.md': 'infra/observation/deploying.md'
          'tutorials/price-provider/whitelisting.md': 'infra/data/whitelisting.md'
          'dev/reference/flare.md': 'dev/reference/network-configs.md'
          'dev/reference/songbird.md': 'dev/reference/network-configs.md'
          'dev/reference/coston-testnet.md': 'dev/reference/network-configs.md'

extra_css:
  - assets/stylesheets/extra.css
extra_javascript:
  - assets/javascripts/mathjax.js
  - assets/javascripts/images.js
  - assets/javascripts/links.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra:
  social:
    - icon: fontawesome/solid/house
      link: https://flare.xyz
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/FlareNetworks
    - icon: fontawesome/brands/github
      link: https://github.com/flare-foundation
    - icon: fontawesome/brands/discord
      link: https://discord.gg/XqNa7Rq
  analytics:
    provider: google
    property: G-3WZ2CSGYV1
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
copyright: >-
  &copy; 2022 Flare Networks. <a href="#__consent">Cookie settings</a>.
site_url: https://docs.flare.network
repo_url: https://github.com/flare-foundation/docs
edit_uri: edit/main/docs/
nav:
  - Home:
    - index.md
  - Concepts:
    - tech/index.md
    - tech/flare-launch-process.md
    - tech/api-portal.md
    - tech/ftso.md
    - tech/governance.md
    - tech/state-connector.md
    - tech/validators.md
    - tech/glossary.md
  - User Guides:
    - user/index.md
    - user/block-explorer.md
    - FTSO Delegation:
      - user/delegation/index.md
      - user/delegation/delegation-overview.md
      - user/delegation/delegation-in-detail.md
      - user/delegation/delegation-faq.md
      - user/delegation/manual-delegation.md
      - user/delegation/reward-claiming.md
      - user/delegation/reward-claiming-in-detail.md
      - user/delegation/reward-claiming-faq.md
      - user/delegation/manual-reward-claiming.md
    - Governance:
      - user/governance/index.md
      - user/governance/voting.md
    - Wallets:
      - user/wallets/index.md
      - user/wallets/bifrost-wallet.md
      - user/wallets/dcent-wallet.md
      - user/wallets/how-to-access-flare-network-with-a-ledger-device.md
      - user/wallets/how-to-access-flare-network-with-a-trezor-device.md
      - user/wallets/how-to-access-flare-network-with-metamask.md
      - user/wallets/safepal-s1-wallet.md
      - user/wallets/brave-wallet.md
  - Infrastructure Guides:
    - infra/index.md
    - FTSO Data Providers:
      - infra/data/index.md
      - infra/data/operating.md
      - infra/data/whitelisting.md
    - Observer Nodes:
      - infra/observation/index.md
      - infra/observation/deploying.md
      - infra/observation/faq.md
    - Validator Nodes:
      - infra/validation/index.md
      - infra/validation/deploying.md
  - Developer Docs:
    - dev/index.md
    - dev/summary.md
    - dev/faq.md
    - Getting Started Guides:
      - dev/getting-started/index.md
      - Contract Deployment:
        - dev/getting-started/deployment/index.md
        - Using Remix: dev/getting-started/deployment/remix.md
    - Reference Guides:
      - dev/reference/index.md
      - dev/reference/contracts.md
      - dev/reference/api-portal.md
      - dev/reference/network-configs.md
  - Exchange Guides:
    - exchange/index.md
    - exchange/architecture.md
    - exchange/delegation.md
    - exchange/troubleshooting.md